version: "3"
services:
  ecar-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_PASSWORD}
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    expose:
      - 1433
    networks:
      - ecar2024

  ecar-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:eCarConnection=Server=${SQL_HOST},1433;Database=${SQL_DB_COMMON};User=${SQL_USER};Password=${SQL_PASSWORD};ConnectRetryCount=0; TrustServerCertificate=True
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}

    ports:
      - 7257:7257
    networks:
      - ecar2024
    links:
      - ecar-sql
    depends_on:
      - ecar-sql

networks:
  ecar2024:
    driver: bridge
